const CAT = {
    FE: 1,
    ST: 2,
    TS: 3,
    BE: 4,
    DE: 5
}

const { FE,ST,TS,BE,DE } = CAT;


export const items = [
    {"skill": "typescript", "type": FE},
    {"skill": "nextjs", "type": FE},
    {"skill": "react", "type": FE},
    {"skill": "scss", "type": ST},
    {"skill": "sonarqube", "type": TS},
    {"skill": "cypress", "type": TS},
    {"skill": "aws", "type": BE},
    {"skill": "react native", "type": FE},
    {"skill": "styled components", "type": FE},
    {"skill": "redux", "type": FE},
    {"skill": "react hooks", "type": FE},
    {"skill": "reactjs", "type": FE},
    {"skill": "azure", "type": BE},
    {"skill": "jest", "type": TS},
    {"skill": "storybook", "type": FE},
    {"skill": "sass", "type": ST},
    {"skill": "node", "type": BE},
    {"skill": "nodejs", "type": BE},
    {"skill": "css", "type": ST},
    {"skill": "html", "type": FE},
    {"skill": "javascript", "type": FE},
    {"skill": "highcharts", "type": FE},
    {"skill": "git", "type": BE},
    {"skill": "angular", "type": FE},
    {"skill": "css3", "type": FE},
    {"skill": "html5", "type": FE},
    {"skill": "expressjs", "type": BE},
    {"skill": "gulp", "type": FE},
    {"skill": "dojo", "type": FE},
    {"skill": "jquery", "type": FE},
    {"skill": "apis", "type": BE},
    {"skill": "svn", "type": BE},
    {"skill": "photoshop", "type": DE},
    {"skill": "xhtml", "type": BE},
    {"skill": "sourcesafe", "type": BE},
    {"skill": "clearcase", "type": BE},
    {"skill": "flash", "type": FE},
    {"skill": "teamsite", "type": BE},
    {"skill": "design", "type": DE},
    {"skill": "svg", "type": DE},
]
