// // src/theme.ts
// const theme = {
//     colors: {
//         primary: '#000',
//         secondary: '#0070f3',
//         background: '#fff',
//         text: '#333',
//         white: '#fff',
//         black: '#000',
//         companyBackground: '#505275',
//         companyActiveBorder: '#333',
//         companyActiveBackground: '#fff',
//         counterBackground: '#3F404B',
//         tabActiveBackground: '#505275',
//         tabInactiveBackground: '#fff',
//         tabActiveColor: '#fff',
//         tabInactiveColor: '#000',
//         containerBackground: '#f1f1f1',
//         lightBlue: '#989cf5',
//         cardBackground: '#fff',
//         linkColor: '#505275',
//         itemType1: '#4F6FFA',
//         itemType2: '#7D6666',
//         itemType3: '#FA9600',
//         itemType4: '#9BA4AB',
//         itemType5: '#1C9BFC',
//     },
//     fontSizes: {
//         title: '1.5rem',
//         paragraph: '1rem',
//         large: '20px',
//         medium: '18px',
//         small: '14px',
//     },
//     spacing: {
//         padding: '20px',
//         margin: '20px',
//         small: '10px',
//         tiny: '5px',
//         huge: '50px',
//     },
//     sizes: {
//         large: '15px',
//         huge: '50px',
//     },
//     widths: {
//         full: '100%',
//         max: '1024px',
//     },
//     icon: {
//         large: '180px',
//     },
//     borderRadius: '0.25rem',
// };
//
// export default theme;

const lightTheme = {
    theme: 'light',
    colors: {
        primary: '#000',
        corporate: '#505275',
        secondary: '#0070f3',
        background: '#fff',
        text: '#333',
        white: '#fff',
        black: '#000',
        companyBackground: '#505275',
        companyActiveBorder: '#333',
        companyActiveBackground: '#fff',
        counterBackground: '#3F404B',
        tabActiveBackground: '#505275',
        tabInactiveBackground: '#fff',
        tabActiveColor: '#fff',
        tabInactiveColor: '#000',
        containerBackground: '#f1f1f1',
        brandContainer: '#f0f0f0',
        lightBlue: '#989cf5',
        cardBackground: '#fff',
        linkColor: '#505275',
        itemType1: '#4F6FFA',
        itemType2: '#7D6666',
        itemType3: '#FA9600',
        itemType4: '#9BA4AB',
        itemType5: '#1C9BFC',
    },
    fontSizes: {
        title: '1.5rem',
        paragraph: '1rem',
        large: '20px',
        medium: '18px',
        small: '14px',
    },
    spacing: {
        padding: '20px',
        margin: '20px',
        small: '10px',
        tiny: '5px',
        huge: '50px',
    },
    sizes: {
        large: '15px',
        huge: '50px',
    },
    widths: {
        full: '100%',
        max: '1024px',
    },
    icon: {
        large: '180px',
    },
    borderRadius: '0.25rem',
};

const darkTheme = {
    theme: 'dark',
    colors: {
        primary: '#fff',
        corporate: '#fff',
        secondary: '#1E90FF',
        background: '#121212',
        text: '#e0e0e0',
        white: '#000',
        black: '#fff',
        companyBackground: '#383838',
        companyActiveBorder: '#e0e0e0',
        companyActiveBackground: '#212121',
        counterBackground: '#fff',
        tabActiveBackground: '#383838',
        tabInactiveBackground: '#212121',
        tabActiveColor: '#e0e0e0',
        tabInactiveColor: '#757575',
        containerBackground: '#1e1e1e',
        brandContainer: '#999',
        lightBlue: '#7289da',
        cardBackground: '#212121',
        linkColor: '#fff',
        itemType1: '#7289da',
        itemType2: '#a66767',
        itemType3: '#ffab40',
        itemType4: '#9BA4AB',
        itemType5: '#2196f3',
    },
    fontSizes: {
        title: '1.5rem',
        paragraph: '1rem',
        large: '20px',
        medium: '18px',
        small: '14px',
    },
    spacing: {
        padding: '20px',
        margin: '20px',
        small: '10px',
        tiny: '5px',
        huge: '50px',
    },
    sizes: {
        large: '15px',
        huge: '50px',
    },
    widths: {
        full: '100%',
        max: '1024px',
    },
    icon: {
        large: '180px',
    },
    borderRadius: '0.25rem',
};

export { lightTheme, darkTheme };